{{- if .Values.ingress.public }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "app.fullname" . }}-public
spec:
  hosts:
  - '{{ .Values.externalUrl.subdomain | default (include "app.fullname" .) }}.{{ .Values.externalUrl.fqdn }}'
  gateways:
  - istio-system/gateway-public
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "app.fullname" . }}
{{- end }}
